//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public Auto()
        {
            this.Entity1 = new HashSet<Entity1>();
        }
    
        public int Id { get; set; }
        public string Boja { get; set; }
    
        public virtual ICollection<Entity1> Entity1 { get; set; }
    }
}
